config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: %i[new edit destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: 'users#index'
  end

  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registration]
  root to: 'static#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_nav.html.erb
<li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <% if current_user.type == 'AdminUser' %>
      <%= link_to "Admin Dashboard", admin_root_path, class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
    <% end %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</li>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], title: "TimeTracker App Alert", sticky: false) %>
<% elsif flash[:error] %>
	<%= js add_gritter(flash[:error], title: "TimeTracker App Error", sticky: false) %>
<% else %>
	<%= js add_gritter(flash[:notice], title: "TimeTracker App Notification", sticky: false) %>
<% end %>

app/views/shared/_audit_log_section.html.erb
<li class="nav-item <%= active?(audit_logs_path) %>">
  <%= link_to "Audit Logs", audit_logs_path, class: "nav-link" %>
</li>

app/views/shared/_employee_nav.html.erb
<li class="nav-item <%= active?(posts_path) %>">
  <%= link_to "Entries", posts_path, class: "nav-link" %>
</li>

<ul class="navbar-nav ml-md-auto">
  <li class="nav-item <%= active?(new_post_path) %>">
     <%= link_to "Request Overtime", new_post_path, class: "nav-link" %>
  </li>
</ul>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light custom-nav">

  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="navbar-toggler-icon"></span>
  </button><%= link_to "Time Tracker", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="navbar-nav">
      <li class="nav-item <%= active?(root_path) %>">
         <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if current_user %>
        <%= render 'shared/employee_nav' if employee? %>

        <%= render 'shared/audit_log_section' if policy(AuditLog).index? %>
        <%= render 'shared/admin_nav' if admin? %>
    </ul>

    <form class="form-inline">
      <input class="form-control mr-sm-2" type="text" />
      <button class="btn btn-primary my-2 my-sm-0" type="submit">
        Search
      </button>
    </form>
    <% end %>
  </div>
</nav>